language: go
go:
- 1.15.x
addons:
  apt:
    packages:
    - snapd

env:
- PATH=/snap/bin:$PATH
before_install:
  - if [ ! -z $TRAVIS_TAG ]; then openssl aes-256-cbc -K $encrypted_c7b8c1fd25b9_key -iv $encrypted_c7b8c1fd25b9_iv -in snap.login.enc -out snap.login -d; fi

install:
# needed for the snap pipe:
  - sudo snap install snapcraft --classic
  - if [ ! -z $TRAVIS_TAG ]; then snapcraft login --with snap.login; fi
  - rm -f snap.login;

jobs:
  include:
    - script:
        - snapcraft cleanbuild || true
        - make release tag=${TRAVIS_TAG:-Unreleased}
      on:
        tags: true
        condition: "$TRAVIS_OS_NAME = linux"
